name: CI/CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run:  docker build -t deepak215/nodejs-ci-cd-demo  .  



      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u " ${{ deepak215 }} " --password-stdin

      - name: Push Docker image
        run: docker push  ${{ secrets.DOCKER_USERNAME }}/nodejs-ci-cd-demo
